### ISSUE TITLE
Données HP/HC incorrectes pour un contrat Tarif Bleu réglementé

### ISSUE THREAD

**Issue by jmcruvellier** [jmcruvellier/little_monkey#58]
### System Health details

![image](https://github.com/jmcruvellier/little_monkey/assets/14132271/444a7a03-1de3-49c6-b8fc-15b18e8de773)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/jmcruvellier/little_monkey/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

l'API kwhstat d'ecojoko n'incrémente pas kwh_hc_ns en heure creuse

### Reproduction steps

Voir les traces

### Debug logs

```text
REPONSE ECOJOKO: {'stat': {'data': [0], 'period': {'this': 1699743600000, 'prev': 1699657200000, 'measure_unit': 'W', 'kwh_hp_ns': 11.9578, 'kwh_hc_ns': 0, 'price': 2.936316196, 'price_prod': 0, 'kwh': 11.9578, 'kwh_prod': 0, 'raw_watt': 852}, 'pricing_details': [{'color': '#7ED2DF', 'id': 2, 'label': 'Heures Pleines'}, {'color': '#679AA2', 'id': 3, 'label': 'Heures Creuses'}], 'axis': {'y': {'max': 7000}}}}
```

**Comment by YohDuDojo** [comment]
Bonjour, effectivement j'ai le même problème sur mon tarif EDF Vert Electrique Option HC HP.

**Comment by jmcruvellier** [comment]
> Bonjour, effectivement j'ai le même problème sur mon tarif EDF Vert Electrique Option HC HP.

Merci pour votre retour, je vais remonter l'information à ecojoko. En attendant leur retour, je suis toujours en train de chercher une solution de contournement.

**Comment by jmcruvellier** [comment]
Bug corrigé dans la version 1.2.0

**Comment by jmcruvellier** [comment]
Bug corrigé dans la version 1.2.0
