### ISSUE TITLE
Conso journalière différente sur HA Energie et l'app/site Ecojoko

### ISSUE THREAD

**Issue by ikekreham** [jmcruvellier/little_monkey#70]
## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1377
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.0 GB
disk_used | 5.3 GB
healthy | true
supported | true
board | green
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), File editor (5.7.0), Ring-MQTT with Video Streaming (5.6.3), Mosquitto broker (6.4.0), Cloudflared (5.0.2), Zigbee2MQTT (1.35.1-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 19 janvier 2024 à 11:02
-- | --
current_recorder_run | 22 janvier 2024 à 18:17
estimated_db_size | 16.27 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/jmcruvellier/little_monkey/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Le cumul journalier n'est pas le même sur HA et sur le site ou l'application Ecojoko: la valeur sur HA est plus élevée que celle qui apparaît sur les outils officiels Ecojoko.

![SCR-20240122-rgnc](https://github.com/jmcruvellier/little_monkey/assets/31365419/75994a00-89df-41e3-b955-5e99af74cee1)
**Valeur dans Home Assistant**

![SCR-20240122-rgxb](https://github.com/jmcruvellier/little_monkey/assets/31365419/1e760cf2-b10d-4fe8-a8f3-dbf2791a06eb)
**Valeur sur le site d'Ecojoko**

La différence semble avoir lieu chaque jour et peut être relativement importante:
Exemple sur la journée du 21/01/2024: 22,57 kWh dans HA contre 19,41 kWh sur le site d'Ecojoko.

Info complémentaire (paramétrage de l'intégration): 
- Au niveau de la Fréquence de rafraîchissement des données (en secondes): j'ai passé la valeur à 10 sec.
- Aucun capteur n'est activé

![SCR-20240122-rkrc](https://github.com/jmcruvellier/little_monkey/assets/31365419/499907fe-163b-4b79-8049-bd8d4eb45d8e)

### Reproduction steps

Comparez les valeurs affichées dans Home Assistant et sur le site ou dans l'application Ecojoko

### Debug logs

```text
J'ai du faire une erreur dans l'activation des logs, je n'ai que les lignes suivantes:

2024-01-22 18:18:04.633 ERROR (MainThread) [custom_components.little_monkey] API HUMSTAT other error: 'subconsumption'
2024-01-22 18:20:10.504 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.ecojoko_consommation_reseau from integration little_monkey has state class total_increasing, but its state is not strictly increasing. Triggered by state 11.1795 (11.1796) with last_updated set to 2024-01-22T17:15:50.765385+00:00. Please create a bug report at https://github.com/jmcruvellier/little_monkey/issues
2024-01-22 19:02:58.516 ERROR (MainThread) [custom_components.little_monkey] API KWHSTAT timeout error
2024-01-22 19:26:02.232 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details timeout error: %s
2024-01-22 19:28:35.231 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details timeout error: %s
2024-01-22 19:30:26.232 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details timeout error: %s
2024-01-22 19:30:40.231 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details timeout error: %s
2024-01-22 19:30:42.348 ERROR (MainThread) [custom_components.little_monkey] API KWHSTAT timeout error
2024-01-22 19:57:56.232 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details timeout error: %s
2024-01-22 19:58:45.231 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details timeout error: %s
2024-01-22 19:59:55.232 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details timeout error: %s
2024-01-22 20:00:32.233 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details timeout error: %s
2024-01-22 20:05:37.231 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details timeout error: %s
2024-01-22 20:05:39.234 ERROR (MainThread) [custom_components.little_monkey] API Realtime timeout error
2024-01-22 20:05:41.236 ERROR (MainThread) [custom_components.little_monkey] API KWHSTAT timeout error
2024-01-22 20:05:53.231 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details timeout error: %s
2024-01-22 20:05:55.233 ERROR (MainThread) [custom_components.little_monkey] API Realtime timeout error
2024-01-22 20:05:57.236 ERROR (MainThread) [custom_components.little_monkey] API KWHSTAT timeout error
2024-01-22 20:06:07.295 ERROR (MainThread) [custom_components.little_monkey] API Pricing Details client error: 502, message='Bad Gateway', url=URL('https://service.ecojoko.com/gateway/41449/device/149493/powerstat/h/2024-01-2220:06')

Je vais essayer de relancer correctement les logs et mettrai à jour le post si vous en avez besoin.
```

**Comment by jmcruvellier** [comment]
Bonjour, merci pour votre retour!
Avez vous la même différence si vous comparez les valeurs du dashboard Énergie de HA avec celles qui sont dans le menu Mesures en choisissant le filtre Semaine?
De mon côté les données sont quasi identiques. 

![Screenshot_2024-01-23-06-58-50-85_7663cba87e8bacb62dc0e4b5b359915f.jpg](https://github.com/jmcruvellier/little_monkey/assets/14132271/78d04d09-2892-4a8e-960a-8594c209035c)

![Screenshot_2024-01-23-06-59-13-84_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/jmcruvellier/little_monkey/assets/14132271/68d04685-4580-4279-8dae-80574be9602a)

**Comment by jmcruvellier** [comment]
Je viens de me rendre compte qu'il manque les données de la soirée dans votre dashboard Énergie. Cela explique la différence sur la journée avec la capture d'écran d'ecojoko.

**Comment by ikekreham** [comment]
Bonjour,

En filtrant sur la semaine, je retrouve également une valeur plus élevée dans Home Assistant que sur l'Ecojoko.

**Pour la journée du lundi 22**
![SCR-20240123-orfk](https://github.com/jmcruvellier/little_monkey/assets/31365419/48954508-a9d2-4587-a06c-1564a0fd8e56)
![SCR-20240123-orno](https://github.com/jmcruvellier/little_monkey/assets/31365419/5a338921-4afb-432f-a1a0-aa14134dd3ea)

**Pour la journée du dimanche 21**
![SCR-20240123-oryi](https://github.com/jmcruvellier/little_monkey/assets/31365419/628ee313-d0ea-4aea-adb4-6b2407c6fe3b)
![SCR-20240123-osha](https://github.com/jmcruvellier/little_monkey/assets/31365419/aebbfd51-5f20-4d2d-9896-866a041fbd67)

**Comment by jmcruvellier** [comment]
> Bonjour,
> 
> En filtrant sur la semaine, je retrouve également une valeur plus élevée dans Home Assistant que sur l'Ecojoko.
> 
> **Pour la journée du lundi 22** ![SCR-20240123-orfk](https://private-user-images.githubusercontent.com/31365419/299006209-48954508-a9d2-4587-a06c-1564a0fd8e56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzQwODIsIm5iZiI6MTcwNzYzMzc4MiwicGF0aCI6Ii8zMTM2NTQxOS8yOTkwMDYyMDktNDg5NTQ1MDgtYTlkMi00NTg3LWEwNmMtMTU2NGEwZmQ4ZTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA2NDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNjE4MDdjMTFhNGIwZDFlNDM0NTUyZTZiYWIzM2M4NWEwNTM5ZTEyOTE5YzM2ZGVhN2E4NTJmMjE2YjNkMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5c2O8aWFe6lCt6fr0FKLVELUgCvHSAyVXNwuukJc1YM) ![SCR-20240123-orno](https://private-user-images.githubusercontent.com/31365419/299006219-5a338921-4afb-432f-a1a0-aa14134dd3ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzQwODIsIm5iZiI6MTcwNzYzMzc4MiwicGF0aCI6Ii8zMTM2NTQxOS8yOTkwMDYyMTktNWEzMzg5MjEtNGFmYi00MzJmLWExYTAtYWExNDEzNGRkM2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA2NDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYzQ1OTU5MzQwMjVkNTBhYzIyMDQ2YTZiNzI5YzE2YzUxZjExMGRmMWY5ZTYzNTJjM2NhNGM1YjNkYmVkM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1r-7XNDyEmV-LJuqGkWgD6KBWphENiPfRM3aqx6qXYI)
> 
> **Pour la journée du dimanche 21** ![SCR-20240123-oryi](https://private-user-images.githubusercontent.com/31365419/299006592-628ee313-d0ea-4aea-adb4-6b2407c6fe3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzQwODIsIm5iZiI6MTcwNzYzMzc4MiwicGF0aCI6Ii8zMTM2NTQxOS8yOTkwMDY1OTItNjI4ZWUzMTMtZDBlYS00YWVhLWFkYjQtNmIyNDA3YzZmZTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA2NDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNDY3MmM0NzQxNDkyNzhhNmQ0ODI1ZTZkOWFhNWQzODRiMTZjMTUyMGIzYTgwNDI4ODJlOTdlZDliNmYyMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sG1W_9I-KwBZpBAGCC52KE03EkGYQ2m7eeY3rjPjsNM) ![SCR-20240123-osha](https://private-user-images.githubusercontent.com/31365419/299006596-aebbfd51-5f20-4d2d-9896-866a041fbd67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzQwODIsIm5iZiI6MTcwNzYzMzc4MiwicGF0aCI6Ii8zMTM2NTQxOS8yOTkwMDY1OTYtYWViYmZkNTEtNWYyMC00ZDJkLTk4OTYtODY2YTA0MWZiZDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA2NDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZDI3NzIyM2IzZmU3YmVlZTU5MWE5ZjA2ZTcxMDZmYTI4MmUwM2Q5NDBkZWY0YjJjNWJjMWZkOWE2MzA4MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TCc_erhV75S0MxP0Oo-UqRD9WdF2HaojEKbwAfV43tg)

Bonjour, pouvez vous me dire si votre problème de différence de données entre celles de l'intégration dans HA et celles d'ecojoko est toujours présente? Cela ne devrait plus être le cas avec la version 1.2.0 qui vient de sortir.

**Comment by alaaghribi** [comment]
Bonsoir. Ah c'est dommage ! Allez-vous tout de même continuer à supporter le module ? Merci beaucoup pour tout ce que vous faites :)!

**Comment by jmcruvellier** [comment]
> Bonjour,
> Pour des raisons financières j’ai malheureusement du stopper mon abonnement EcoJoko et j’ai réexpédié le matériel vendredi soir. Je vous prie de m’excuser mais je ne pourrais donc vous confirmer la correction. 

Aucun soucis, je suis désolé pour vous. Courage

**Comment by jmcruvellier** [comment]
> Bonsoir. Ah c'est dommage ! Allez-vous tout de même continuer à supporter le module ? Merci beaucoup pour tout ce que vous faites :)! 

Vous vous êtes trompé, c'est moi qui développe et maintien l'intégration. 😉

**Comment by alaaghribi** [comment]
Désolé j'ai pas fait attention sur les pseudos 😁 allez j'ai envie de dire heureusement pour nous 😜
