### ISSUE TITLE
Plus de données remontées quand un problème d'authentification survient avec les APIs d'ecojoko

### ISSUE THREAD

**Issue by jmcruvellier** [jmcruvellier/little_monkey#71]
## System Information

version | core-2024.1.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 1004
Installed Version | 1.34.0
Stage | running
Available Repositories | 1382
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 6.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), Studio Code Server (5.15.0), Samba share (12.2.0), Cloudflared (5.1.1), Fusion (2024.1.11)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 4
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21 janvier 2024 à 06:19
-- | --
current_recorder_run | 2 février 2024 à 10:38
estimated_db_size | 444.95 MiB
database_engine | mysql
database_version | 11.2.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/jmcruvellier/little_monkey/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Quand les serveurs d'API d'ecojoko retournent une erreur d'authentification, l'intégration ne remonte plus de données dans Home Assistant. Un rechargement de l'intégration permet de contourner le problème.

![image](https://github.com/jmcruvellier/little_monkey/assets/14132271/c134e329-411b-4178-be98-11236739b796)

![image](https://github.com/jmcruvellier/little_monkey/assets/14132271/8a3e52ff-dae3-402d-9bea-7b4692c31869)

### Reproduction steps

N/A

### Debug logs

```text
N/A
```

**Comment by Dan512512** [comment]
Micrologiciel : 1.1.0
Matériel : 1.00.32

Toujours pas d'affichage des HC, malgré un redémarrage

![ecojoko](https://github.com/jmcruvellier/little_monkey/assets/156787939/6df00abc-048f-4298-8c8d-a153aa29eb0d)

**Comment by jmcruvellier** [comment]
> Micrologiciel : 1.1.0
> Matériel : 1.00.32
> 
> Toujours pas d'affichage des HC, malgré un redémarrage
> 
> ![ecojoko](https://github.com/jmcruvellier/little_monkey/assets/156787939/6df00abc-048f-4298-8c8d-a153aa29eb0d)
> 

Bonjour, merci pour votre retour. Grâce à un autre utilisateur de l'intégration j'ai pu comprendre d'où vient le problème chez ecojoko (pas facile sans documentation).
J'ai commencé à travailler dessus mais ça va prendre quelques jours avant de pouvoir fixer le problème définitivement.

**Comment by Dan512512** [comment]
‌Bonjour Jean-Marc,

Avant tout, félicitations pour ton travail qui relie Ecojoko et Home Assistant !

Merci pour avoir répondu à mon signalement,

Bon courage à toi pour la résolution de ce problème.
 


‌‌‌‌Cordialement, 

Daniel (grand débutant domotique/home Assistant)

 



De : "jmcruvellier" ***@***.***>
A : "jmcruvellier/little_monkey" ***@***.***>,"Dan512512" ***@***.***>,"Comment" ***@***.***>
Envoyé: lundi 5 Février 2024 12:25
Objet : Re: [jmcruvellier/little_monkey] Plus de données remontées quand un problème d'authentification survient avec les APIs d'ecojoko (Issue #71)
 

 


Micrologiciel : 1.1.0
Matériel : 1.00.32

Toujours pas d'affichage des HC, malgré un redémarrage

ecojoko.PNG (view on web)


Bonjour, merci pour votre retour. Grâce à un autre utilisateur de l'intégration j'ai pu comprendre d'où vient le problème chez ecojoko (pas facile sans documentation).
J'ai commencé à travailler dessus mais ça va prendre quelques jours avant de pouvoir fixer le problème définitivement.

**Comment by Dan512512** [comment]
Re, je effectué une réinstallation complète HA et Petit Singe Micrologiciel : 1.1.0.
Toujours pas d'heures creuses .

![ecojoko, re-bug !](https://github.com/jmcruvellier/little_monkey/assets/156787939/a057daf0-4b09-418a-949f-04b8dffac627)

**Comment by jmcruvellier** [comment]
> Re, je effectué une réinstallation complète HA et Petit Singe Micrologiciel : 1.1.0.
> Toujours pas d'heures creuses .
> 
> ![ecojoko, re-bug !](https://github.com/jmcruvellier/little_monkey/assets/156787939/a057daf0-4b09-418a-949f-04b8dffac627)
> 

Bonjour, je suis au courant (par contre vous avez posté sur le mauvais bug report 😉).
Grâce à un autre utilisateur de l'intégration j'ai pu comprendre la source du problème (qui est côté ecojoko), et trouver une solution de contournement. J'ai commencé à y travailler dessus mais ça va prendre un peu de temps car ça remet en question un bonne partie de la logique que j'ai développé.

**Comment by jmcruvellier** [comment]
Bug corrigé dans la version 1.1.0

**Comment by Dan512512** [comment]
Bonjour,

Merci, le problème est résolu :)

**Comment by jmcruvellier** [comment]
> Bonjour,
> 
> Merci, le problème est résolu :)

Bonjour, merci pour votre retour!
