### ISSUE TITLE
Plus de données ecojoko depuis le 28/03/24 23:00

### ISSUE THREAD

**Issue by ChrisDany84** [jmcruvellier/little_monkey#76]
## System Information

version | core-2024.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1473
Downloaded Repositories | 6
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.0 GB
disk_used | 8.3 GB
healthy | true
supported | true
board | green
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.1), File editor (5.8.0), Terminal & SSH (9.10.0), ESPHome (2024.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 2
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20 mars 2024 à 08:16
-- | --
current_recorder_run | 25 mars 2024 à 14:06
estimated_db_size | 55.88 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/jmcruvellier/little_monkey/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Dans mes différents tableaux de bord, plus de màj. Les données instantanées sont figées, la consommation d'électricité est à zéro pour aujourd'hui, le graphique s'est interrompu hier à 23h

### Reproduction steps

1. Les données ecojoko sont gelées dans HA
2. En consultation sur l'appli ecojoko, la mise à jour se fait toujours 
3.j'avais cependant observé au début de la panne que l'accès aux données ecojoko était aussi interrompu sur Internet
...

### Debug logs

```text
ND. Je viens juste d'activer le debug
```

**Comment by jmcruvellier** [comment]
Bonjour, il y a eu un soucis hier soir du côté d'ecojoko. Essayez de recharger l'intégration pour voir si les données remontent de nouveau dans Home Assistant.

**Comment by ChrisDany84** [comment]
Bonjour,
Merci pour la réponse.
Ne sachant pas comment recharger l'intégration, j'ai fait un redémarrage HA qui a corrigé le problème et fait remonter les stats d'électricité.
Bonne journée.

29 mars 2024 09:43:46 jmcruvellier ***@***.***>:
