### ISSUE TITLE
Problème identification lors de la configuration

### ISSUE THREAD

**Issue by MJoanDaSilva** [jmcruvellier/little_monkey#77]
## System Information

version | core-2024.5.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.34.0
Stage | running
Available Repositories | 1398
Downloaded Repositories | 2
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6 mai 2024 à 10:29
-- | --
current_recorder_run | 6 mai 2024 à 15:50
estimated_db_size | 0.83 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/jmcruvellier/little_monkey/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Lors de la configuration à l'étape d'entrée le nom, utilisateur et mot de passe, un message d'erreur inconnue apparait. J'ai bien vérifié les identifiants mais le message apparaît à chaque tentative même en ayant changé le mot de passe.

### Reproduction steps

1.Ajouter Little Monkey
2.Enter le nom, les credentials et valider
3.Une erreur inconnue est survenue.
...

### Debug logs

```text
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.little_monkey
Source: custom_components/little_monkey/config_flow.py:151
intégration: Petit Singe (documentation, problèmes)
S'est produit pour la première fois: 15:52:16 (4 occurrences)
Dernier enregistrement: 16:24:02

Something really wrong happened!
Traceback (most recent call last):
  File "/config/custom_components/little_monkey/api.py", line 405, in _cookiesapi_wrapper
    raise LittleMonkeyApiClientAuthenticationError(
custom_components.little_monkey.api.LittleMonkeyApiClientAuthenticationError: Invalid credentials

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/little_monkey/api.py", line 190, in async_get_cookiesdata
    return await self._cookiesapi_wrapper(data=payload_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/little_monkey/api.py", line 424, in _cookiesapi_wrapper
    raise LittleMonkeyApiClientError(
custom_components.little_monkey.api.LittleMonkeyApiClientError: Something really wrong happened!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/little_monkey/config_flow.py", line 151, in async_step_user
    await self._get_cookies(
  File "/config/custom_components/little_monkey/config_flow.py", line 199, in _get_cookies
    await client.async_get_cookiesdata()
  File "/config/custom_components/little_monkey/api.py", line 192, in async_get_cookiesdata
    raise LittleMonkeyApiClientError(
custom_components.little_monkey.api.LittleMonkeyApiClientError: Something really wrong happened!
```

**Comment by jmcruvellier** [comment]
Sans nouvelles de votre part, je clos l'incident. N'hésitez pas à me recontacter si le problème est toujours d'actualité.
