### ISSUE TITLE
Données de conso remontées non correctes 

### ISSUE THREAD

**Issue by Vinsssounet** [jmcruvellier/little_monkey#81]
## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1460
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 28.0 GB
disk_used | 5.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | green
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), Zigbee2MQTT (1.41.0-1), File editor (5.8.0), Terminal & SSH (9.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 1
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28 octobre 2024 à 18:52
-- | --
current_recorder_run | 31 octobre 2024 à 12:56
estimated_db_size | 188.21 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/jmcruvellier/little_monkey/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Bonjour !

Les données de consommation remontées par Home Assistant avec l'intégration Ecojoko différent de celles de l'appli de base (qui elles sont bien plus proches de mes relevés de conso sur ma facture). Elles sont toujours supérieures dans HA.
![Screenshot_20241105-164752](https://github.com/user-attachments/assets/7da5de00-f5b3-4968-aaae-e644b94cd414)
![Screenshot_20241105-164928](https://github.com/user-attachments/assets/94def9e5-2c21-455f-9e6f-255afc28f45d)

### Reproduction steps

Que ce soit le jour ou le mois, ma conso remontée est bien plus élevée dans HA.

Que la journée d'hier : 13.62 kWh dans Ecojoko contre 17.12 dans HA.

### Debug logs

```text
Je n'ai pas de log pertinent à ma connaissance.
```

**Comment by jmcruvellier** [comment]
Bonjour, merci pour votre retour d'expérience!
Il y a une différence entre la version actuelle de l'intégration et l'application ecojoko. Cette dernière applique des corrections à posteriori aux données (basés sur des calculs côté ecojoko), alors que l'intégration ne fait que récupérer ces données à un instant T (donc non encore corrigées).
Je vais clôturer cet incident car il ne s'agit pas d'un big de l'intégration, mais d'une fonctionnalité qui ne peut pas être développée avec les APIs actuelles d'ecojoko car elles n'ont pas été développées à la base pour l'usage qu'il en est fait par cette intégration (pour rappel c'est un développement non officiel).
NOTE: je suis en discussion avec ecojoko pour que cela soit possible dans la prochaine version (ainsi que d'autres fonctionnalités), mais pas de date à vous communiquer à ce jour.
Je vous invite d'ailleurs à remplir ce questionnaire si vous ne l'avez pas déjà fait: https://docs.google.com/forms/d/1t1EuxEy3ixpZwMCIkoNYGvxKx_GUgKY4qzwXyxIFw84

**Comment by Link0Darck** [comment]
> Bonjour, merci pour votre retour d'expérience! Il y a une différence entre la version actuelle de l'intégration et l'application ecojoko. Cette dernière applique des corrections à posteriori aux données (basés sur des calculs côté ecojoko), alors que l'intégration ne fait que récupérer ces données à un instant T (donc non encore corrigées). Je vais clôturer cet incident car il ne s'agit pas d'un big de l'intégration, mais d'une fonctionnalité qui ne peut pas être développée avec les APIs actuelles d'ecojoko car elles n'ont pas été développées à la base pour l'usage qu'il en est fait par cette intégration (pour rappel c'est un développement non officiel). NOTE: je suis en discussion avec ecojoko pour que cela soit possible dans la prochaine version (ainsi que d'autres fonctionnalités), mais pas de date à vous communiquer à ce jour. Je vous invite d'ailleurs à remplir ce questionnaire si vous ne l'avez pas déjà fait: https://docs.google.com/forms/d/1t1EuxEy3ixpZwMCIkoNYGvxKx_GUgKY4qzwXyxIFw84

Bonjour,
Quand est t'il de votre retour car depuis Dimanche 24 Novembre tout mes donnée sont erroné car sinon la je devrais payer 20 000€ de facture d'électricité et je voulais ouvrir un ticket mais je voulais savoir si il existé pas un ouvert actuellement.
Cordialement

**Comment by jmcruvellier** [comment]
> Bonjour, Quand est t'il de votre retour car depuis Dimanche 24 Novembre tout mes donnée sont erroné car sinon la je devrais payer 20 000€ de facture d'électricité et je voulais ouvrir un ticket mais je voulais savoir si il existé pas un ouvert actuellement. Cordialement

Bonjour, il n'y a pas de solutions à court terme, je n'ai pas de date pour une potentielle évolution de l'intégration (je suis toujours en attente de discussions avec ecojoko sur ce sujet).
Pour l'instant, vous pouvez corriger les données aberrantes dans les statistiques. C'est ce que d'autres utilisateurs et moi faisons quand cela se produit.

**Comment by Link0Darck** [comment]
> > Bonjour, Quand est t'il de votre retour car depuis Dimanche 24 Novembre tout mes donnée sont erroné car sinon la je devrais payer 20 000€ de facture d'électricité et je voulais ouvrir un ticket mais je voulais savoir si il existé pas un ouvert actuellement. Cordialement
> 
> Bonjour, il n'y a pas de solutions à court terme, je n'ai pas de date pour une potentielle évolution de l'intégration (je suis toujours en attente de discussions avec ecojoko sur ce sujet). Pour l'instant, vous pouvez corriger les données aberrantes dans les statistiques. C'est ce que d'autres utilisateurs et moi faisons quand cela se produit.

Bonjour,
Pouvez vous me dire comment corriger les données à qu'elle endroit exactement s'il vous plait.
Merci d'avance

**Comment by jmcruvellier** [comment]
> > > Bonjour, Quand est t'il de votre retour car depuis Dimanche 24 Novembre tout mes donnée sont erroné car sinon la je devrais payer 20 000€ de facture d'électricité et je voulais ouvrir un ticket mais je voulais savoir si il existé pas un ouvert actuellement. Cordialement
> > 
> > Bonjour, il n'y a pas de solutions à court terme, je n'ai pas de date pour une potentielle évolution de l'intégration (je suis toujours en attente de discussions avec ecojoko sur ce sujet). Pour l'instant, vous pouvez corriger les données aberrantes dans les statistiques. C'est ce que d'autres utilisateurs et moi faisons quand cela se produit.
> 
> Bonjour,
> Pouvez vous me dire comment corriger les données à qu'elle endroit exactement s'il vous plait.
> Merci d'avance

Il faut aller dans les Outils de développement, puis dans l'onglet statistiques. Là vous recherchez l'entité à corriger et vous éditez les valeurs en cliquant sur l'icône à droite.
